### PR TITLE
Update discordbot.cr

### PR DESCRIPTION
**Pull request by Computer-Genuis**
changed terms slightly. please accept.

### CODE REVIEW

**Comment by kantenkugel** [comment]
Not sure if some kind of reminder (be careful) should be in the terms... Thats not really what terms are for

**Comment by Computer-Genuis** [comment]
How about a section about if the bot is abused, it will be removed from that server? 

Damaging the community image and all that

**Comment by greenbigfrog** [comment]
I'm gonna close this for now, since I'm actually not really interested in changing the terms, since they're more then sufficient already.

**Comment by Computer-Genuis** [comment]
I removed the second part, but added "delay". I recall that you send some people will hold cold wallets. Maybe add them into the disclaimer as well.

**Pull request closed without merging**
